# Use the official pgAdmin image
FROM dpage/pgadmin4

# Set environment variables (values will be injected via docker-compose)
ENV PGADMIN_DEFAULT_EMAIL=admin@example.com
ENV PGADMIN_DEFAULT_PASSWORD=secret

# Expose pgAdmin web interface port
EXPOSE 80